version: '3'
services:
  crds-maestro:
    build: .
    image: crdschurch/crds-maestro
    container_name: crds-maestro
    ports:
     - "4000:4000"
    # volumes:
    #  - .:/maestro
    #  # - C:\temp:/microclients/legacy
    #  - ./local:/microclients
    #  #- C:/temp/new_phoenix/crds-angular/crossroads.net/assets/:/maestro/apps/crossroads_interface/priv/static/js/legacy
    #  #- C:/temp/new_phoenix/crds-angular/crossroads.net/assets/:/microclients/legacy
    environment:
     # are all of these necessary if we are building legacy outside of container?
     - CRDS_APP_CLIENT_ENDPOINT
     - CRDS_CMS_CLIENT_ENDPOINT
     - CRDS_CMS_SERVER_ENDPOINT
     - CRDS_COOKIE_DOMAIN=localhost
     - CRDS_ENV=int
     - CRDS_GATEWAY_CLIENT_ENDPOINT
     - CRDS_GATEWAY_SERVER_ENDPOINT
     - CRDS_STREAMSPOT_API_KEY
     - CRDS_STREAMSPOT_SSID
     - MIX_ENV=dev
     - MAESTRO_RUN_IN_DOCKER=true

  crds-apache:
    build: 
      context: ./apache
    image: crdschurch/crds-apache
    container_name: crds-apache
    ports:
     - "8000:80"
    environment:
     # are all of these necessary if we are building legacy outside of container?
     - CRDS_CMS_SERVER_ENDPOINT=https://contentint.crossroads.net/
     - CRDS_GATEWAY_SERVER_ENDPOINT=https://gatewayint.crossroads.net/gateway/
     - CRDS_PRERENDER_IO_KEY
     - CRDS_SERVER_ALIAS=int.crossroads.net
     - CRDS_SERVER_NAME=localhost
     - CRDS_SERVICES_SERVER_ENDPOINT=https://gatewayint.crossroads.net/
     - CRDS_WEBSITE_PATH=/usr/local/apache2/htdocs
     - MAESTRO_HOSTNAME=crds-maestro
     - MAESTRO_PORT=4000