apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maestro-phoenix
spec:
  revisionHistoryLimit: 0
  replicas: 2
  selector:
    matchLabels:
      app: maestro-phoenix
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: maestro-phoenix
    spec:
      containers:
        - name: maestro-phoenix
          image: crdschurch/crds-maestro-phoenix:$DOCKER_TAG
          imagePullPolicy: Always
          resources:
            limits:
              memory: "512Mi"
              cpu: "400m"
            requests:
              memory: "256Mi"
              cpu: "100m"
          env:
            - name: CRDS_ENV
              value: "$CRDS_ENV"
            - name: MIX_ENV
              value: "prod"
            - name: CRDS_PRERENDER_IO_KEY
              value: "$CRDS_PRERENDER_IO_KEY"
          ports:
            - containerPort: 8000
              name: cowboy
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 20