apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maestro-varnish
spec:
  revisionHistoryLimit: 0
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: maestro-varnish
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: maestro-varnish
    spec:
      containers:
      - name: maestro-varnish
        image: crdschurch/crds-maestro-varnish:$DOCKER_TAG
        imagePullPolicy: Always
        env:
        - name: VCL_CONFIG
          value: "/etc/varnish/config/prod.vcl"
        ports:
        - containerPort: 80
          name: http