apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: maestro-phoenix
spec:
  revisionHistoryLimit: 0
  minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: maestro-phoenix
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: maestro-phoenix
    spec:
      volumes:
      - name: maestro-phoenix-ssl-vol
        secret:
          secretName: crossroads-ssl
      containers:
      - name: maestro-phoenix
        image: crdschurch/crds-maestro:$DOCKER_TAG
        imagePullPolicy: Always
        resources:
          limits:
            memory: "512Mi"
            cpu: "400m"
          requests:
            memory: "256Mi"
            cpu: "100m"
        env:
        - name: MIX_ENV
          value: "prod"
        - name: MAESTRO_SSL
          value: "true"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: maestro-phoenix-ssl-vol
          mountPath: "/certificates"
          readOnly: true