apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: maestro-phoenix-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: maestro-phoenix
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 75