apiVersion: v1
kind: Service
metadata:
  name: maestro-phoenix-service
  labels:
    app: maestro
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: maestro-phoenix