version: '3'
services:
  maestro:
    image: crdschurch/crds-maestro-phoenix:${DOCKER_TAG:-development}
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile-prod
      args:
        - CRDS_APP_CLIENT_ENDPOINT
        - CRDS_CMS_CLIENT_ENDPOINT
        - CRDS_CMS_SERVER_ENDPOINT
        - CRDS_COOKIE_DOMAIN
        - CRDS_ENV
        - CRDS_GATEWAY_CLIENT_ENDPOINT
        - CRDS_GATEWAY_SERVER_ENDPOINT
        - CRDS_MP_BASE_URL
        - CRDS_STREAMSPOT_API_KEY
        - CRDS_STREAMSPOT_SSID
        - CRDS_GOOGLE_API_KEY
        - CRDS_ROLLCALL_FORM_ID
        - MAESTRO_HOSTNAME
        - MAESTRO_NAME_EXTENSION
        - MIX_ENV=prod
        - ROBOTS_TXT_FILENAME
        - TIMEZONE
    container_name: crds-maestro
    ports:
      - "8000:8000"
    environment:
      - CRDS_PRERENDER_IO_KEY